# Configuración del proyecto NER
model:
  name: "distilbert-base-multilingual-cased"  # Modelo base de HuggingFace
  max_length: 128
  num_labels: 9  # Ajustar según tu dataset

dataset:
  name: "conll2003"  # Dataset de HuggingFace
  train_split: "train"
  validation_split: "validation" 
  test_split: "test"
  text_column: "tokens"
  label_column: "ner_tags"

training:
  output_dir: "./models"
  num_train_epochs: 3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  warmup_steps: 500
  logging_steps: 100
  save_steps: 500
  eval_steps: 500
  save_total_limit: 2
  evaluation_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_f1"
  greater_is_better: true

data_paths:
  raw_data: "./data/raw"
  processed_data: "./data/processed"
  models_dir: "./models"

logging:
  use_wandb: false  # Cambiar a true si quieres usar Weights & Biases
  project_name: "ner-training"